# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CORENAME: pcsx2
    CORE_ARGS: -DCMAKE_BUILD_TYPE=Release

before_script:
  - cd pcsx2/GS/parallel-gs
  - git submodule sync Granite
  - git submodule update --init Granite
  - cd Granite
  - git submodule sync third_party/volk
  - git submodule update --init third_party/volk
  - git submodule sync third_party/khronos/vulkan-headers
  - git submodule update --init third_party/khronos/vulkan-headers

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-msvc19.yml'

  # MacOS
  - project: 'libretro-infrastructure/ci-templates'
    file: 'osx-cmake-x86.yml'

  # MacOS arm64
#  - project: 'libretro-infrastructure/ci-templates'
#    file: 'osx-cmake-arm64.yml'

  # Linux
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-msvc19-cmake-x86_64
    - .core-defs

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-defs
  variables:
    EXTRA_PATH: bin

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .libretro-osx-cmake-x86
    - .core-defs
  variables:
    EXTRA_PATH: libretro

# MacOS arm64
#libretro-build-osx-arm64:
#  extends:
#    - .libretro-osx-cmake-arm64
#    - .core-defs
